name: Update JSON File

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B auto/update-artists

      - name: Run update script
        run: node update-json.js

      - name: Commit changes
        id: commit
        run: |
          git add artists.json
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            git commit -m "Auto-update artists.json [skip ci]"
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: ${{ steps.commit.outputs.no_changes == 'false' }}
        run: git push --force --set-upstream origin auto/update-artists

      - name: Create Pull Request
        if: ${{ steps.commit.outputs.no_changes == 'false' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-update artists.json [skip ci]"
          branch: auto/update-artists
          title: "🔄 Auto-update artists.json"
          body: |
            This pull request was automatically generated by a scheduled GitHub Action.
            It updates the `artists.json` file with the latest post counts.
          base: main
